# lens, sort, title, author, source, row, subgenre, [urls], [keywords], why, note
A="America Abroad"; P="Power"; W="Work"; E="Equality"; F="Faith"; O="Order"; G="Government"; M="The Media"; B="The Bomb"
C2=[
# FRANCE 1968
("france","1968-05-30","Allocution radiodiffusée du général de Gaulle (30 May 1968)","Charles de Gaulle","Fondation Charles de Gaulle","Power","executive power",["http://www.charles-de-gaulle.org/announcement/30-mai-1968-declaration-radiodiffusee-du-general-de-gaulle-dans-lequel-il-annonce-la-dissolution-de-lassemblee-nationale-le-maintien-du-premier-ministre-le-remaniement-du-gouvernement-l/","https://www.dhr.history.vt.edu/modules/eu/mod05_1968/evidence_detail_08.html"],["Assemblée","dissol"],"The president answers the May 1968 student and strike revolt by dissolving the Assembly; the template for how France's presidents respond to the street.","In French from the Charles de Gaulle Foundation. An English translation is at the Virginia Tech teaching module (secondary host). No primary text of the Grenelle agreements or of the student movement could be verified."),
# LEBANON
("lebanon","1989-10-22","The Taif Agreement (National Reconciliation Accord)","Lebanese parliamentarians, meeting at Taif","UN Peacemaker / Lebanese Parliament","Equality","civil rights law",["https://peacemaker.un.org/lebanon-taifaccords89","https://www.un.int/lebanon/sites/www.un.int/files/Lebanon/the_taif_agreement_english_version_.pdf"],["Taif","Lebanon"],"Ended the civil war and set the sectarian power-sharing still in force.",""),
("lebanon","2004-09-02","UN Security Council Resolution 1559","United Nations Security Council","UN document S/RES/1559(2004)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/1559(2004)"],["Lebanon"],"Called for foreign forces to leave Lebanon and for militias, meaning Hezbollah, to disband.","UN viewer is JavaScript; open to confirm."),
("lebanon","2006-08-11","UN Security Council Resolution 1701","United Nations Security Council","UN document S/RES/1701(2006)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/1701(2006)"],["Lebanon"],"Ended the 2006 Israel-Hezbollah war and set the terms the 2024 ceasefire still cites.","UN viewer is JavaScript; open to confirm."),
("lebanon","1926-05-23","Constitution of Lebanon","Republic of Lebanon","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Lebanon_2004"],["Lebanon","Parliament"],"The state's governing text; the sectarian quotas live in it and the Taif amendments.","Date is the original 1926 text; the page is the text as amended to 2004."),
# SYRIA
("syria","2012-06-30","Final Communiqué of the Action Group for Syria (Geneva Communiqué)","Action Group for Syria","United Nations","America Abroad","military intervention",["https://www.un.org/News/dh/infocus/Syria/FinalCommuniqueActionGroupforSyria.pdf","https://peacemaker.un.org/syria-genevacommunique2012"],["Syria","transition"],"The plan for a political transition that was never carried out.",""),
("syria","2013-09-27","UN Security Council Resolution 2118","United Nations Security Council","UN document S/RES/2118(2013)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/2118(2013)"],["Syria"],"Required Syria to give up its chemical weapons after the Ghouta attack.","UN viewer is JavaScript; open to confirm."),
("syria","2015-12-18","UN Security Council Resolution 2254","United Nations Security Council","UN document S/RES/2254(2015)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/2254(2015)"],["Syria"],"The UN road map for a ceasefire, a constitution and elections.","UN viewer is JavaScript; open to confirm."),
("syria","2003-12-12","Syria Accountability and Lebanese Sovereignty Restoration Act of 2003","U.S. Congress","Pub. L. 108-175, GovInfo","America Abroad","military intervention",["https://www.govinfo.gov/content/pkg/PLAW-108publ175/pdf/PLAW-108publ175.pdf"],[],"The first U.S. sanctions law aimed at the Syrian government.",""),
# IRAQ
("iraq","1991-04-03","UN Security Council Resolution 687","United Nations Security Council","UN document S/RES/687(1991)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/687(1991)"],["Iraq"],"The ceasefire terms after the Gulf War, including weapons inspections.","UN viewer is JavaScript; open to confirm."),
("iraq","2002-11-08","UN Security Council Resolution 1441","United Nations Security Council","UN document S/RES/1441(2002)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/1441(2002)"],["Iraq"],"The 'final opportunity' resolution on inspections, argued over before the 2003 invasion.","UN viewer is JavaScript; open to confirm."),
("iraq","2005-10-15","Constitution of Iraq","Republic of Iraq","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Iraq_2005"],["Iraq","Federal"],"The post-invasion governing text; federalism and Islam's role are still contested.",""),
("iraq","2008-11-17","Agreement on the Withdrawal of United States Forces from Iraq (Status of Forces Agreement)","United States and Iraq","U.S. Department of State","America Abroad","military intervention",["https://2009-2017.state.gov/documents/organization/122074.pdf","https://www.state.gov/wp-content/uploads/2019/02/08-1217-Iraq-Withdrawal.pdf"],[],"The agreement that set the 2011 U.S. withdrawal date.",""),
# SAUDI ARABIA
("saudi-arabia","1980-01-23","State of the Union Address (the Carter Doctrine)","Jimmy Carter","Public Papers of the Presidents (American Presidency Project)","America Abroad","military intervention",["https://www.presidency.ucsb.edu/documents/the-state-the-union-address-delivered-before-joint-session-the-congress-1"],["Persian Gulf"],"The U.S. pledge to defend the Persian Gulf, the basis of the American security role in Saudi Arabia.","An American text about the Gulf; kept under Saudi Arabia and Iran."),
("saudi-arabia","1992-03-01","Basic Law of Governance of Saudi Arabia","Kingdom of Saudi Arabia","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Saudi_Arabia_2005"],["Saudi","King"],"The kingdom's governing text: the Quran as constitution, the king's powers.",""),
("saudi-arabia","2002-03-28","Arab Peace Initiative","League of Arab States, proposed by Crown Prince Abdullah of Saudi Arabia","League of Arab States, English text","America Abroad","Israel-Palestine policy",["https://www.un.org/unispal/document/auto-insert-178331/","https://www.mfa.gov.il/mfa/foreignpolicy/peace/mfadocuments/pages/arab%20peace%20initiative.aspx"],["Arab","Israel"],"The Saudi-led offer of normalization for a return to the 1967 lines; central again in Gaza diplomacy.",""),
("saudi-arabia","2016-04-25","Saudi Vision 2030","Kingdom of Saudi Arabia","Vision 2030 official site","Work","trade and globalization",["https://www.vision2030.gov.sa/media/rc0b5oy1/saudi_vision203.pdf","https://www.vision2030.gov.sa/en"],["Vision"],"The economic plan to move beyond oil.",""),
# TURKEY
("turkey","1923-07-24","Treaty of Lausanne","Allied Powers and Turkey","Ministry of Foreign Affairs of the Republic of Turkey","America Abroad","alliances and commitments",["https://www.mfa.gov.tr/lausanne-peace-treaty-part-i_-political-clauses.en.mfa","https://avalon.law.yale.edu/20th_century/lausanne.asp"],["Lausanne","Turkey"],"The treaty that set modern Turkey's borders and minority rules.",""),
("turkey","1952-02-18","Turkey and Greece accession to the North Atlantic Treaty","NATO","NATO official texts","America Abroad","alliances and commitments",["https://www.nato.int/cps/en/natohq/declassified_137344.htm","https://www.nato.int/cps/en/natohq/topics_52044.htm"],["Turkey"],"Turkey joins NATO, anchoring the alliance's southeast flank.",""),
("turkey","1982-11-07","Constitution of the Republic of Turkey (as amended)","Republic of Turkey","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Turkey_2017"],["Turkey","President"],"The governing text; the 2017 amendments created the executive presidency.",""),
# SOUTH AFRICA
("south-africa","1955-06-26","The Freedom Charter","Congress of the People","African National Congress","Equality","civil rights law",["https://www.anc1912.org.za/the-freedom-charter-2/","https://www.sahistory.org.za/archive/freedom-charter-0"],["Freedom Charter","South Africa"],"The anti-apartheid movement's founding statement of rights.",""),
("south-africa","1964-04-20","Statement from the Dock at the Rivonia Trial","Nelson Mandela","African National Congress","Equality","civil rights law",["https://www.mandela.gov.za/mandela_speeches/1964/640420_trial.htm","https://www.anc1912.org.za/nelson-mandelas-statement-from-the-dock-at-the-rivonia-trial/"],["prepared to die","ideal"],"'An ideal for which I am prepared to die.'",""),
("south-africa","1996-12-10","Constitution of the Republic of South Africa, 1996","Constitutional Assembly of South Africa","Government of South Africa","Equality","civil rights law",["https://www.gov.za/documents/constitution-republic-south-africa-1996","https://www.concourt.org.za/index.php/constitution"],["Constitution","South Africa"],"The post-apartheid constitution, a model for rights-based constitutions.",""),
("south-africa","2023-12-29","Application Instituting Proceedings: South Africa v. Israel (Genocide Convention)","Republic of South Africa","International Court of Justice","America Abroad","Israel-Palestine policy",["https://www.icj-cij.org/sites/default/files/case-related/192/192-20231228-app-01-00-en.pdf"],[],"South Africa's case against Israel at the ICJ, now at the center of the Gaza argument.","PDF; text not machine-checked."),
# UK
("uk","1215-06-15","Magna Carta","King John and the barons of England","Avalon Project, Yale","Power","constitutional restraints",["https://avalon.law.yale.edu/medieval/magframe.asp"],["Magna Carta"],"The oldest text on limiting a ruler's power, behind the American Constitution.",""),
("uk","1689-12-16","The English Bill of Rights","Parliament of England","Avalon Project, Yale","Power","constitutional restraints",["https://avalon.law.yale.edu/17th_century/england.asp"],["Parliament","Bill of Rights"],"Parliament's limits on the Crown; a direct source for the American Bill of Rights.",""),
("uk","1783-09-03","Treaty of Paris (1783)","Great Britain and the United States","Avalon Project, Yale","America Abroad","alliances and commitments",["https://avalon.law.yale.edu/18th_century/paris.asp"],["Treaty","Britain"],"Britain recognizes the United States.",""),
("uk","1946-03-05","The Sinews of Peace (the 'Iron Curtain' speech)","Winston Churchill","The Churchill Centre / Winston Churchill Foundation","America Abroad","alliances and commitments",["https://winstonchurchill.org/resources/speeches/1946-1963-elder-statesman/the-sinews-of-peace/"],["Iron Curtain","Fulton"],"Britain's wartime leader calls for a Western alliance against the USSR.",""),
("uk","2017-03-29","Prime Minister's letter to President of the European Council triggering Article 50","Theresa May","UK Government","America Abroad","alliances and commitments",["https://www.gov.uk/government/publications/prime-ministers-letter-to-donald-tusk-triggering-article-50"],["Article 50"],"The formal start of Britain's exit from the European Union.",""),
# GERMANY
("germany","1949-05-23","Basic Law for the Federal Republic of Germany","Parliamentary Council","Federal Ministry of Justice, English translation","Power","constitutional restraints",["https://www.gesetze-im-internet.de/englisch_gg/"],["Basic Law"],"Postwar Germany's constitution, built to prevent another dictatorship.",""),
("germany","1963-01-22","Treaty on Franco-German Cooperation (Élysée Treaty)","Konrad Adenauer and Charles de Gaulle","Federal Foreign Office / Elysee","America Abroad","alliances and commitments",["https://www.bundesregierung.de/breg-en/service/archive/elysee-treaty","https://www.cvce.eu/en/obj/the_elysee_treaty_22_january_1963-en-9b2d5db7-2e90-4e00-b6ae-4d9b4e8f4e84.html"],["Franco-German","cooperation"],"Reconciliation between France and Germany, the core of the European project.",""),
("germany","1990-08-31","Treaty on the Establishment of German Unity (Unification Treaty)","Federal Republic of Germany and the German Democratic Republic","German Historical Institute, English translation","America Abroad","alliances and commitments",["https://ghdi.ghi-dc.org/sub_document.cfm?document_id=223"],["Unity","Germany"],"The treaty that merged East and West Germany.",""),
("germany","2022-02-27","Policy statement by Chancellor Olaf Scholz (the Zeitenwende speech)","Olaf Scholz","Federal Government of Germany","America Abroad","alliances and commitments",["https://www.bundesregierung.de/breg-en/news/policy-statement-by-olaf-scholz-chancellor-of-the-federal-republic-of-germany-and-member-of-the-german-bundestag-27-february-2022-in-berlin-2008378"],["Zeitenwende","Ukraine"],"Germany's turn on defence spending after Russia's invasion of Ukraine.",""),
# JAPAN
("japan","1945-07-26","Potsdam Declaration: Proclamation Defining Terms for Japanese Surrender","Truman, Churchill and Chiang Kai-shek","Avalon Project, Yale","America Abroad","military intervention",["https://avalon.law.yale.edu/wwii/potsdam.asp","https://avalon.law.yale.edu/20th_century/decade17.asp"],["Japan","surrender"],"The terms Japan accepted after the bombs.",""),
("japan","1947-05-03","The Constitution of Japan","Government of Japan","Prime Minister of Japan and His Cabinet","Power","constitutional restraints",["https://japan.kantei.go.jp/constitution_and_government_of_japan/constitution_e.html"],["Article 9","renounce"],"Article 9's renunciation of war, written under the Occupation.",""),
("japan","1960-01-19","Treaty of Mutual Cooperation and Security between Japan and the United States","Japan and the United States","Ministry of Foreign Affairs of Japan","America Abroad","alliances and commitments",["https://www.mofa.go.jp/region/n-america/us/q&a/ref/1.html"],["Security","Japan"],"The bilateral security treaty still in force.",""),
# INDIA
("india","1947-08-15","Indian Independence Act 1947","Parliament of the United Kingdom","UK Parliament, legislation.gov.uk","Power","constitutional restraints",["https://www.legislation.gov.uk/ukpga/Geo6/10-11/30/contents/enacted"],["India","Dominion"],"The law that ended British rule and created India and Pakistan.",""),
("india","1950-01-26","Constitution of India","Constituent Assembly of India","Constitute Project / Government of India","Power","constitutional restraints",["https://www.constituteproject.org/constitution/India_2016"],["India","Fundamental Rights"],"The world's largest democracy's governing text.",""),
("india","1972-07-02","Simla Agreement","India and Pakistan","Ministry of External Affairs, India","America Abroad","alliances and commitments",["https://mea.gov.in/in-focus-article.htm?19005/Simla+Agreement+July+2+1972"],["Simla","Kashmir"],"The India-Pakistan framework that still governs the Line of Control.",""),
("india","2005-07-18","Joint Statement by President Bush and Prime Minister Singh (civil nuclear cooperation)","George W. Bush and Manmohan Singh","The White House archives","The Bomb","arms control and treaties",["https://georgewbush-whitehouse.archives.gov/news/releases/2005/07/20050718-6.html"],["nuclear","India"],"The U.S.-India nuclear deal that ended India's nuclear isolation.",""),
# MEXICO
("mexico","1848-02-02","Treaty of Guadalupe Hidalgo","United States and Mexico","National Archives","America Abroad","military intervention",["https://www.archives.gov/milestone-documents/treaty-of-guadalupe-hidalgo"],["Guadalupe","Mexico"],"The treaty that ended the Mexican-American War and moved the border.",""),
("mexico","1917-01-16","The Zimmermann Telegram","Arthur Zimmermann","National Archives","America Abroad","military intervention",["https://www.archives.gov/education/lessons/zimmermann"],["Zimmermann","Mexico"],"Germany's offer to Mexico that helped bring the United States into World War I.",""),
("mexico","1917-02-05","Constitution of Mexico, 1917","Constituent Congress of Mexico","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Mexico_2015"],["Mexico","Article"],"The first constitution to write in social rights, land and labor.",""),
("mexico","1994-01-01","North American Free Trade Agreement","Governments of the United States, Mexico and Canada","Office of the United States Trade Representative","Work","trade and globalization",["https://ustr.gov/trade-agreements/free-trade-agreements/north-american-free-trade-agreement-nafta"],["NAFTA"],"The trade pact the 2018 USMCA replaced.",""),
# ARGENTINA
("argentina","1853-05-01","Constitution of the Argentine Nation","General Constituent Congress","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Argentina_1994"],["Argentine","Nation"],"The constitution modeled on the American one.","Text as amended 1994."),
("argentina","1965-12-16","UN General Assembly Resolution 2065 (XX): Question of the Falkland Islands (Malvinas)","United Nations General Assembly","UN document A/RES/2065(XX)","America Abroad","military intervention",["https://docs.un.org/en/A/RES/2065(XX)"],["Falkland"],"The UN call for Britain and Argentina to negotiate the islands' status.","UN viewer is JavaScript; open to confirm."),
("argentina","1982-05-25","Argentina's Falklands conflict, UN Security Council Resolution 502","United Nations Security Council","UN document S/RES/502(1982)","America Abroad","military intervention",["https://docs.un.org/en/S/RES/502(1982)"],["Falkland"],"The resolution demanding Argentina's withdrawal at the start of the 1982 war.","UN viewer is JavaScript; open to confirm."),
# AUSTRALIA
("australia","1901-01-01","Commonwealth of Australia Constitution Act","Imperial Parliament","Museum of Australian Democracy / Australian government","Power","constitutional restraints",["https://www.legislation.gov.au/C1900A00063/latest/text","https://www.moadoph.gov.au/democracy/australian-constitution/"],["Constitution","Commonwealth"],"Australia's founding constitution.",""),
("australia","1951-09-01","Security Treaty between Australia, New Zealand and the United States (ANZUS)","Australia, New Zealand and the United States","Avalon Project, Yale","America Abroad","alliances and commitments",["https://avalon.law.yale.edu/20th_century/usmu001.asp"],["Australia","Pacific"],"The Pacific alliance that still anchors American strategy in the region.",""),
("australia","2021-09-15","Joint Leaders Statement on AUKUS","Joe Biden, Scott Morrison and Boris Johnson","The White House","America Abroad","alliances and commitments",["https://bidenwhitehouse.archives.gov/briefing-room/statements-releases/2021/09/15/joint-leaders-statement-on-aukus/"],["AUKUS"],"The submarine pact aimed at China.",""),
# BRAZIL
("brazil","1988-10-05","Constitution of the Federative Republic of Brazil","Constituent Assembly of Brazil","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Brazil_2017"],["Brazil","Federal"],"The 'citizen constitution' that ended military rule.",""),
("brazil","2010-05-17","Joint Declaration of Iran, Turkey and Brazil (the Tehran Declaration)","Iran, Turkey and Brazil","Brazilian Ministry of Foreign Affairs / IAEA","The Bomb","arms control and treaties",["https://www.iaea.org/sites/default/files/publications/documents/infcircs/2010/infcirc799.pdf"],["Tehran"],"Brazil and Turkey's attempt to broker an Iran nuclear deal outside the great powers.","PDF; text not machine-checked."),
# INDONESIA
("indonesia","1955-04-24","Final Communiqué of the Asian-African Conference of Bandung","Asian-African Conference","Digital Archive, Indonesia / Library","America Abroad","alliances and commitments",["https://www.bandungspirit.org/IMG/pdf/bandung_final_communique.pdf","https://www.cvce.eu/en/obj/final_communique_of_the_asian_african_conference_bandung_24_april_1955-en-676237fd-ce81-4a19-b5ca-5b5c8e0b4bba.html"],["Bandung"],"The founding statement of the non-aligned movement.",""),
("indonesia","1945-08-18","Constitution of the Republic of Indonesia (as amended)","Republic of Indonesia","Constitute Project, English translation","Power","constitutional restraints",["https://www.constituteproject.org/constitution/Indonesia_2002"],["Indonesia","Pancasila"],"The Pancasila constitution; the 2002 amendments ended Suharto-era rule.",""),
# ITALY
("italy","1929-02-11","Lateran Treaty","Kingdom of Italy and the Holy See","Avalon Project, Yale","Faith","religion in public life",["https://avalon.law.yale.edu/20th_century/lateran.asp"],["Holy See","Italy"],"The treaty that made Vatican City a state.",""),
("italy","1947-12-22","Constitution of the Italian Republic","Constituent Assembly of Italy","Senate of the Italian Republic, English translation","Power","constitutional restraints",["https://www.senato.it/sites/default/files/media-documents/Costituzione_INGLESE_2023.pdf","https://www.constituteproject.org/constitution/Italy_2012"],["Constitution","Italian"],"Postwar Italy's governing text, written to bar a return of fascism.",""),
("italy","1957-03-25","Treaty establishing the European Economic Community (Treaty of Rome)","Six founding states, including Italy","EUR-Lex","America Abroad","alliances and commitments",["https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:11957E/TXT"],["European Economic Community"],"The treaty that began the common market, signed in Rome.",""),
# TECH
("tech","1890-07-02","Sherman Antitrust Act","U.S. Congress","National Archives","Government","regulation and the administrative state",["https://www.archives.gov/milestone-documents/sherman-anti-trust-act"],["Sherman","trust"],"The first law against monopoly, the basis for every later action against big companies.",""),
("tech","1934-06-19","Communications Act of 1934","U.S. Congress","Pub. L. 73-416, GovInfo","The Media","platforms and attention",["https://www.govinfo.gov/content/pkg/COMPS-1409/pdf/COMPS-1409.pdf","https://www.govinfo.gov/content/pkg/STATUTE-48/pdf/STATUTE-48-Pg1064.pdf"],[],"The law that created the FCC and still frames broadcast and telecom regulation.",""),
("tech","1945-07-01","As We May Think","Vannevar Bush","The Atlantic","The Media","information and misinformation",["https://www.theatlantic.com/magazine/archive/1945/07/as-we-may-think/303881/"],["Memex","As We May Think"],"The essay that imagined the web and the personal machine for managing information.",""),
("tech","1955-08-31","A Proposal for the Dartmouth Summer Research Project on Artificial Intelligence","John McCarthy, Marvin Minsky, Nathaniel Rochester, Claude Shannon","Stanford University, John McCarthy archive","Government","state capacity and competence",["http://jmc.stanford.edu/articles/dartmouth/dartmouth.pdf"],[],"The proposal that gave the field its name.","PDF; text not machine-checked."),
("tech","1974-12-31","Privacy Act of 1974","U.S. Congress","Pub. L. 93-579, GovInfo","Order","surveillance",["https://www.govinfo.gov/content/pkg/STATUTE-88/pdf/STATUTE-88-Pg1896.pdf"],[],"The first U.S. law on what the government may do with personal data.","PDF; text not machine-checked."),
("tech","1996-02-08","47 U.S. Code Section 230: Protection for private blocking and screening of offensive material","U.S. Congress","Legal Information Institute, Cornell Law School","The Media","platforms and attention",["https://www.law.cornell.edu/uscode/text/47/230"],["interactive computer service"],"The liability shield for online platforms, the legal basis of the modern internet.","Cornell LII is a legal library. Passed as part of the Telecommunications Act, already in the matrix."),
("tech","2016-04-27","General Data Protection Regulation","European Parliament and Council","EUR-Lex","Order","surveillance",["https://eur-lex.europa.eu/eli/reg/2016/679/oj"],["personal data"],"The European model for data privacy that U.S. states and companies answer to.",""),
("tech","2023-10-30","Executive Order 14110: Safe, Secure, and Trustworthy Development and Use of Artificial Intelligence","Joe Biden","Federal Register","Government","regulation and the administrative state",["https://www.federalregister.gov/documents/2023/11/01/2023-24283/safe-secure-and-trustworthy-development-and-use-of-artificial-intelligence"],["Artificial Intelligence"],"The first broad U.S. executive action on AI safety.",""),
("tech","2024-06-13","Regulation (EU) 2024/1689 (the AI Act)","European Parliament and Council","EUR-Lex","Government","regulation and the administrative state",["https://eur-lex.europa.eu/eli/reg/2024/1689/oj"],["artificial intelligence"],"The first comprehensive law on AI, in force in Europe.",""),
("tech","2025-01-23","Executive Order 14179: Removing Barriers to American Leadership in Artificial Intelligence","Donald J. Trump","Federal Register","Government","regulation and the administrative state",["https://www.federalregister.gov/documents/2025/01/31/2025-02172/removing-barriers-to-american-leadership-in-artificial-intelligence"],["Artificial Intelligence"],"Reverses the 2023 order; the swing in U.S. AI policy.",""),
# RUSSIA
("russia","1994-12-05","Memorandum on Security Assurances in connection with Ukraine's accession to the Treaty on the Non-Proliferation of Nuclear Weapons (Budapest Memorandum)","Russia, the United Kingdom, the United States and Ukraine","UN document A/49/765","The Bomb","arms control and treaties",["https://digitallibrary.un.org/record/188969","https://docs.un.org/en/A/49/765"],[],"Ukraine gave up its nuclear weapons for assurances Russia later broke.","UN viewers are JavaScript; open to confirm."),
("russia","1997-05-27","Founding Act on Mutual Relations, Cooperation and Security between NATO and the Russian Federation","NATO and Russia","NATO official texts","America Abroad","alliances and commitments",["https://www.nato.int/cps/en/natohq/official_texts_25468.htm"],["Founding Act","Russia"],"The agreement Russia now says NATO broke.",""),
("russia","2007-02-10","Speech and the Following Discussion at the Munich Conference on Security Policy","Vladimir Putin","President of Russia, English","America Abroad","alliances and commitments",["http://en.kremlin.ru/events/president/transcripts/24034"],["Munich","unipolar"],"Putin's break with the West, years before Ukraine.",""),
("russia","2014-03-18","Address by President of the Russian Federation (Crimea)","Vladimir Putin","President of Russia, English","America Abroad","military intervention",["http://en.kremlin.ru/events/president/news/20603"],["Crimea"],"The annexation of Crimea.",""),
("russia","2022-02-24","Address by the President of the Russian Federation","Vladimir Putin","President of Russia, English","America Abroad","military intervention",["http://en.kremlin.ru/events/president/transcripts/67843"],["special military operation"],"The announcement of the full invasion of Ukraine.",""),
# CHINA
("china","1899-09-06","The Open Door Notes","John Hay","Avalon Project, Yale","America Abroad","alliances and commitments",["https://avalon.law.yale.edu/19th_century/hay.asp"],["Open Door","China"],"The first American statement of a China policy.",""),
("china","1984-12-19","Joint Declaration of the Government of the United Kingdom and the Government of the People's Republic of China on the Question of Hong Kong","United Kingdom and the People's Republic of China","UN Treaty Series / UK Government","America Abroad","alliances and commitments",["https://www.cap1.gov.hk/","https://treaties.un.org/doc/Publication/UNTS/Volume%201399/volume-1399-I-23391-English.pdf"],[],"The 'one country, two systems' promise behind the Hong Kong protests.","PDF; text not machine-checked."),
("china","2017-07-20","A Next Generation Artificial Intelligence Development Plan","State Council of the People's Republic of China","DigiChina, Stanford University (translation)","Government","state capacity and competence",["https://digichina.stanford.edu/work/full-translation-chinas-new-generation-artificial-intelligence-development-plan-2017/"],["Artificial Intelligence"],"China's plan to lead the world in AI by 2030.","Translation hosted by a university project; no official English text."),
("china","2020-01-15","Economic and Trade Agreement between the Government of the United States and the Government of the People's Republic of China (Phase One)","United States and China","Office of the United States Trade Representative","Work","trade and globalization",["https://ustr.gov/phase-one"],["Phase One"],"The 2020 trade truce, and the commitments China did not meet.",""),
]
