# lens, year, sortdate, title, author, source, row, subgenre, urls(list, first that verifies wins), keywords that must appear on the page, why
C = [
# ISRAEL
("israel","1917","1917-11-02","Balfour Declaration","Arthur James Balfour","Letter to Lord Rothschild, British Foreign Office","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/balfour.asp"],["national home","Jewish"],"Britain's statement of support for a Jewish national home in Palestine; the earliest document most later ones answer."),
("israel","1947","1947-11-29","UN General Assembly Resolution 181 (II), the Partition Plan","United Nations General Assembly","UN document A/RES/181(II)","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/un181.asp","https://www.un.org/unispal/document/auto-insert-185393/","https://undocs.org/A/RES/181(II)"],["Partition","Jewish State"],"The UN vote to divide Palestine into a Jewish and an Arab state; the legal starting point for both sides' claims."),
("israel","1948","1948-05-14","Declaration of the Establishment of the State of Israel","Provisional Council of State, David Ben-Gurion","Israel Ministry of Foreign Affairs / Knesset","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/israel.asp","https://main.knesset.gov.il/en/about/pages/declaration.aspx"],["Declaration","State of Israel"],"Israel's founding statement, issued the day the British Mandate ended."),
("israel","1967","1967-11-22","UN Security Council Resolution 242","United Nations Security Council","UN document S/RES/242(1967)","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/un242.asp","https://undocs.org/S/RES/242(1967)"],["withdrawal","territories"],"The land-for-peace resolution after the Six-Day War; cited in every later negotiation."),
("israel","1993","1993-09-13","Declaration of Principles on Interim Self-Government Arrangements (Oslo I)","Israel and the Palestine Liberation Organization","Signed at Washington, D.C.","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/isrplo.asp","https://peacemaker.un.org/israelopt-osloaccord93"],["Interim","Palestinian"],"The first agreement in which Israel and the PLO recognized each other; the framework of the peace process."),
("israel","1988","1988-08-18","Covenant of the Islamic Resistance Movement (Hamas)","Hamas","Hamas founding charter, English translation","America Abroad","Israel-Palestine policy",
 ["https://avalon.law.yale.edu/20th_century/hamas.asp"],["Islamic Resistance Movement","Palestine"],"Hamas's founding text; the other side's own statement of aims. Sensitive: editor to decide whether to include."),
# IRAN
("iran","1979","1979-12-03","Constitution of the Islamic Republic of Iran","Islamic Republic of Iran","Constitute Project, English translation","America Abroad","military intervention",
 ["https://www.constituteproject.org/constitution/Iran_1989","https://www.constituteproject.org/constitution/Iran_1989.pdf"],["Islamic Republic","Guardian"],"Iran's governing text since the revolution; defines the Supreme Leader's role the news keeps returning to."),
("iran","1981","1981-01-19","Algiers Accords: Declaration of the Government of Algeria","Government of Algeria, for Iran and the United States","International Legal Materials","America Abroad","military intervention",
 ["https://www.iranhrc.org/","https://avalon.law.yale.edu/20th_century/iran_01.asp"],["Algeria","Iran"],"The agreement that ended the hostage crisis and set up the claims tribunal."),
("iran","1987","1987-07-20","UN Security Council Resolution 598","United Nations Security Council","UN document S/RES/598(1987)","America Abroad","military intervention",
 ["https://undocs.org/S/RES/598(1987)","https://www.un.org/securitycouncil/content/resolutions-adopted-security-council-1987"],["598","Iran"],"The ceasefire resolution that ended the Iran-Iraq war."),
("iran","2015","2015-07-14","Joint Comprehensive Plan of Action","Iran, China, France, Germany, Russia, United Kingdom, United States, EU","U.S. Department of State, text of the agreement","America Abroad","military intervention",
 ["https://2009-2017.state.gov/documents/organization/245317.pdf","https://www.state.gov/wp-content/uploads/2019/02/jcpoa.pdf","https://undocs.org/S/2015/544"],["Joint Comprehensive Plan of Action","Iran"],"The 2015 nuclear deal: what it limited, and what the 2018 withdrawal ended."),
("iran","2018","2018-05-08","National Security Presidential Memorandum 11: Ceasing U.S. Participation in the JCPOA","Donald J. Trump","Public Papers of the Presidents","America Abroad","military intervention",
 ["SEARCH:presidency.ucsb.edu national security presidential memorandum ceasing United States participation JCPOA May 8 2018"],["Joint Comprehensive Plan of Action"],"The order that withdrew the United States from the deal; the proximate cause of later escalation."),
# CANADA
("canada","1817","1817-04-28","Rush-Bagot Agreement","Richard Rush and Charles Bagot","Exchange of notes, Avalon Project","America Abroad","alliances and commitments",
 ["https://avalon.law.yale.edu/19th_century/rushba.asp"],["Great Lakes","armed vessels"],"The demilitarization of the Great Lakes; the first step toward the undefended border."),
("canada","1940","1940-08-18","Ogdensburg Agreement: Joint Statement on Defense","Franklin D. Roosevelt and W. L. Mackenzie King","Joint statement issued at Ogdensburg, New York","America Abroad","alliances and commitments",
 ["https://avalon.law.yale.edu/wwii/ogdensburg.asp","SEARCH:Ogdensburg Agreement 1940 joint statement Permanent Joint Board on Defence text"],["Permanent Joint Board","Defense"],"The agreement that made the two countries one defence partnership."),
("canada","1982","1982-04-17","Constitution Act, 1982 (including the Canadian Charter of Rights and Freedoms)","Parliament of Canada","Justice Laws Website, Government of Canada","Power","constitutional restraints",
 ["https://laws-lois.justice.gc.ca/eng/const/page-12.html","https://laws-lois.justice.gc.ca/eng/const/FullText.html"],["Constitution Act, 1982","Charter"],"Canada's own founding text, patriated in 1982; the neighbour's constitutional model."),
("canada","1988","1988-01-02","Canada-United States Free Trade Agreement","Governments of Canada and the United States","Text of the agreement","Work","trade and globalization",
 ["SEARCH:Canada-United States Free Trade Agreement 1988 full text official"],["Free Trade Agreement","Canada"],"The agreement that began today's integrated North American economy."),
("canada","2018","2018-11-30","United States-Mexico-Canada Agreement","Governments of the United States, Mexico and Canada","Office of the United States Trade Representative","Work","trade and globalization",
 ["https://ustr.gov/trade-agreements/free-trade-agreements/united-states-mexico-canada-agreement/agreement-between"],["Agreement","Canada"],"The trade pact now under strain."),
("canada","2025","2025-02-01","Executive Order 14193: Imposing Duties to Address the Flow of Illicit Drugs Across Our Northern Border","Donald J. Trump","Federal Register","Work","trade and globalization",
 ["SEARCH:federalregister.gov executive order 14193 imposing duties illicit drugs northern border"],["Northern Border","Canada"],"The first tariffs on Canada of the second Trump term."),
# NATO
("nato","1949","1949-04-04","The North Atlantic Treaty","Parties to the North Atlantic Treaty","NATO official texts","America Abroad","alliances and commitments",
 ["https://www.nato.int/cps/en/natohq/official_texts_17120.htm"],["Article 5","armed attack"],"The founding text, including the Article 5 mutual defence pledge."),
("nato","1967","1967-12-14","The Future Tasks of the Alliance (the Harmel Report)","North Atlantic Council","NATO official texts","America Abroad","alliances and commitments",
 ["https://www.nato.int/cps/en/natohq/official_texts_26700.htm"],["Harmel","deterrence"],"The statement that paired deterrence with detente and set NATO's course for decades."),
("nato","2001","2001-09-12","Statement by the North Atlantic Council on the terrorist attacks (Article 5)","North Atlantic Council","NATO official texts","America Abroad","alliances and commitments",
 ["https://www.nato.int/cps/en/natohq/official_texts_18553.htm","https://www.nato.int/docu/speech/2001/s010912a.htm"],["Article 5","attack"],"The only time Article 5 has been invoked."),
("nato","2014","2014-09-05","Wales Summit Declaration","Heads of State and Government, North Atlantic Council","NATO official texts","America Abroad","alliances and commitments",
 ["https://www.nato.int/cps/en/natohq/official_texts_112964.htm"],["Wales","2%"],"The pledge to spend two percent of GDP on defence, after Russia's seizure of Crimea."),
("nato","2025","2025-06-25","The Hague Summit Declaration","Heads of State and Government, North Atlantic Council","NATO official texts","America Abroad","alliances and commitments",
 ["SEARCH:nato.int The Hague Summit Declaration 25 June 2025 official text 5%"],["Hague","5%"],"The five-percent defence spending commitment."),
# FRANCE
("france","1789","1789-08-26","Declaration of the Rights of Man and of the Citizen","National Constituent Assembly","Avalon Project, Yale Law School","Equality","civil rights law",
 ["https://avalon.law.yale.edu/18th_century/rightsof.asp"],["Rights of Man","Citizen"],"France's founding statement of rights and popular sovereignty; the language of every later protest."),
("france","1958","1958-10-04","Constitution of 4 October 1958 (the Fifth Republic)","French Republic","Constitutional Council of France, English translation","Power","executive power",
 ["https://www.conseil-constitutionnel.fr/en/constitution-of-4-october-1958"],["Constitution","President of the Republic"],"The text that gave France its strong presidency and Article 49.3, the tool used to pass the budget and pension changes."),
("france","1966","1966-03-07","Letter from President de Gaulle to President Johnson on France's withdrawal from NATO's integrated command","Charles de Gaulle","Foreign Relations of the United States","America Abroad","alliances and commitments",
 ["SEARCH:de Gaulle letter to Johnson March 7 1966 NATO integrated command withdrawal text history.state.gov"],["NATO","France"],"France leaves NATO's command structure but not the alliance."),
("france","2003","2003-02-14","Address by Dominique de Villepin to the UN Security Council on Iraq","Dominique de Villepin","UN Security Council verbatim record S/PV.4701","America Abroad","military intervention",
 ["https://undocs.org/S/PV.4701","SEARCH:Villepin Security Council 14 February 2003 speech text Iraq old Europe"],["Iraq","Villepin"],"The French case against the Iraq war, a landmark in the transatlantic split."),
("france","2023","2023-04-17","Address to the French people on the pension reform","Emmanuel Macron","Elysee, official English translation","Work","wages and bargaining power",
 ["SEARCH:elysee.fr Macron address to the French 17 April 2023 pension reform English"],["pension","Macron"],"The president's answer to the 2023 strikes, a precedent for today's protests."),
]
